### ISSUE TITLE
Bubble Sort code in C++ and update the Sources section

### ISSUE THREAD

**Issue by JASKAMAL22** [ayan-biswas0412/AlgoDocs#30]
**Please describe the proposed algorithm you want to add to this repo.**
This is an implementation of Bubble Sort.

**Describe sources (if you want to follow any)**
A clear and concise source code along with the modification in the sources section.

**Describe the languages in which you want to implement the algorithm**
C++

**Are you working on this? (Yes/No)**
Yes

**Comment by ayan-biswas0412** [comment]
Closing via #36
