### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by TishaJhabak1014** [ayan-biswas0412/AlgoDocs#32]
**Please describe your proposed algorithm you want to add in this repo.**
This issue will let me add one of the most common algorithms under divide and conquer , i.e merge sort implemented in python.
It will enrich the set of algorithms.

**Describe the languages in which you want to implement the algorithm**
The algorithm will be implemented in python.

**Are you working on this? (Yes/No)**
yes

**Comment by TishaJhabak1014** [comment]
@ayan-biswas0412 Issue created, kindly add the labels.

**Comment by ayan-biswas0412** [comment]
Closing via #47
